# Generated by Django 5.0.3 on 2024-03-10 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogtag_alter_blog_options_blog_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors_blogs', to='blogs.blogauthors'),
        ),
    ]
