# Generated by Django 5.0.3 on 2024-03-10 06:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogauthors_alter_blogtag_id_blog_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthors',
            options={'verbose_name': 'Blog Author', 'verbose_name_plural': 'Blog Author(s)'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
